# Generated by Django 4.1.5 on 2023-01-10 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habitcompletedate',
            unique_together={('complete_date', 'habit')},
        ),
    ]
